version: '3.8'
services:
  nip05-bot:
    image: nip05bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DENO_ENV=production
    restart: unless-stopped